#!/bin/sh

swp_count=`cat /sys/kernel/debug/ieee80211/phy2/wil6210/sweep_dump | grep Counter | awk '{print $2}'`

cat /sys/kernel/debug/ieee80211/phy2/wil6210/sweep_dump  | sed -n -e 's/\(\[\)//p' |  grep -w ${swp_count} >> plz_work
